spring.application.name=spring-jwt
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/E-BANK?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=walid123
spring.jpa.hibernate.ddl-auto = create-drop
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
secret.key=9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338


spring.ai.mcp.server.name=bank-mcp-server
spring.main.banner-mode=off
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.capabilities.tool=true
#spring.main.web-application-type=none
logging.file.name=./target/starter-webmvc-server.log

#spring.ai.mcp.server.sse-message-endpoint=/mcp/message
#spring.ai.mcp.server.sse-endpoint=/sse

# Configuration MCP

spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcendpoint=/mcp

#logging.pattern.console=
#
#logging.level.org.hibernate=ERROR
#logging.level.io.modelcontextprotocol=ERROR