spring.application.name=mcp-client
server.port=9090
#Hugging CONFIGURATION
#spring.ai.openai.api-key=
#spring.ai.openai.base-url=https://router.huggingface.co/together
##spring.ai.openai.chat.options.model=meta-llama/Llama-3.2-3B-Instruct-Turbo
##spring.ai.openai.chat.options.model=nvidia/Llama-3.1-Nemotron-70B-Instruct-HF
#spring.ai.openai.chat.options.model=Qwen/Qwen2.5-7B-Instruct-Turbo
#spring.ai.openai.chat.options.temperature=0.7

# Groq CONFIGURATION
#spring.ai.openai.api-key=
#spring.ai.openai.base-url=https://api.groq.com/openai
#spring.ai.openai.chat.options.model=llama-3.1-8b-instant

#OPENAI CONFIGURATION
spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.chat.options.model=gpt-4.1
spring.ai.openai.chat.options.temperature=1
spring.ai.openai.chat.options.max-completion-tokens=1024

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.request-timeout=360s
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers-config.json